### ISSUE TITLE
pprint function didn't output context in output window

### ISSUE THREAD

**Issue by jonike** [paulwinex/pw_MultiScriptEditor#8]
Hi, The editor is awesome. The error occur in print function when  output.
Example:
from pprint import pprint
pprint({"hello":"world"}
Output:
{
:
}
No any context in key, value output.

**Comment by paulwinex** [comment]
Yes, is old issue. I make new version now, maybe i can fix it.

**Comment by jonike** [comment]
Thanks, sir.That would be great!
